#debug: true
security.user.password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.test.context.cache: DEBUG #To know exactly how many contexts have been loaded and cached.

server:
  context-path: /@project.artifactId@/



management:
  context-path: /mgmt
  security:
    enabled: false

endpoints:
  actuator:
    path: /
  liquibase:
    enabled: true


spring:
  rabbitmq:
    host: dockerhost
    port: 5672
    username: guest
    password: guest

  jpa:
    show-sql: true

info:
  application:
    artifactId: @project.artifactId@
    groupId: @project.groupId@

springfox.documentation.swagger.v2.path: /api-docs


---

spring:
  profiles: migration
  datasource:
      url: @jdbc.url@
      username: @jdbc.username@
      password: @jdbc.password@
      driver-class-name: @jdbc.driverClassName@
  jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop



